articles/urls.py
from django.urls import path
from . import views


app_name = "articles"
urlpatterns = [
    path('', views.articles_list, name="list"),
    path('<slug>', views.article_detail, name="detail"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('contact/', views.contact),
    path('services/', views.services),
    path('articles/', include('articles.urls')),
    
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    
    #    in add thumbnail ax
    image = models.ImageField(default='default.jpg', blank = True)
    # add in author


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + ' ...'

articles/views.py
from django.shortcuts import render, HttpResponse
from . import models



def articles_list(request):
    articles = models.Article.objects.all().order_by('-date')
    
    args = {'articles':articles}
    
    return render(request, 'articles/articleslist.html', args)


def article_detail(request, slug):
    # return HttpResponse(slug)
    article = models.Article.objects.get(slug=slug)
    # queri mizanim
    return render(request, 'articles/article_detail.html', {'article':article})

blog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    return render(request, 'about.html')

def home(request):
    #return HttpResponse('home Page...')
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

def services(request):
    return render(request, 'services.html')

articles/templates/articles/article_detail.html
{%extends "base.html"%}
{%block content%}
<div class='artcle.detal'>
    <div class='article'>
        {% if article.image %}
        <img src="{{article.image.url}}" alt="">
        {% endif %}
        
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
    </div>
</div>
{%endblock%}

articles/templates/articles/articleslist.html
{% extends "base.html" %}
{% block title %}
    مقالات
{% endblock  %}

{% block content %}
<div class="container">
    <h1>صفحه مقالات</h1>
    
    <a href="/" title="صفحه اصلی">صفحه آغازین</a>
    </br>
    <a href="/about/" title="درباره">دربارم میدونی؟</a>
    </br>
    <a href="/services/" title="خدمات">خدمات قابل ارائه</a>
    </br>
    <a href="/contact/" title="تماس بگیر باهام">تماس با من</a>
    </br>
    <a href="/articles/" title="مقالات و اخبار">مقالات</a>

    {% for article in articles %}
    <h2><a href = "{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>    
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    {% endfor %}
</div>
{% endblock content %}

templates/about.html
{% extends "base.html" %}
{% block title %}
    درباره بهمن
{% endblock  %}

{% block content %}
<div class="container">
    
    <h1>من همینم که میبینی</h1>
    <a href="/" title="صفحه اصلی">صفحه آغازین</a>
    </br>
    <a href="/about/" title="درباره">دربارم میدونی؟</a>
    </br>
    <a href="/services/" title="خدمات">خدمات قابل ارائه</a>
    </br>
    <a href="/contact/" title="تماس بگیر باهام">تماس با من</a>
    </br>
    <a href="/articles/" title="مقالات و اخبار">مقالات</a>

    {% for article in articles %}
    <h2><a href = "{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>    
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    {% endfor %}
</div>
{% endblock content %}
       

templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <title>  
            {% block title %}          
        Articles   
            {% endblock %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <h2><a href={% url 'articles:list'%}>LOGO</a>

        </h2>
        <div class = 'wrapper'>
        {% block content %}
        {% endblock content %}
        </div>
    </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}
    تماس با بهمن
{% endblock  %}

{% block content %}
<div class="container">
    <h1>تماس با بهمن</h1>
    
    <a href="/" title="صفحه اصلی">صفحه آغازین</a>
    </br>
    <a href="/about/" title="درباره">دربارم میدونی؟</a>
    </br>
    <a href="/services/" title="خدمات">خدمات قابل ارائه</a>
    </br>
    <a href="/contact/" title="تماس بگیر باهام">تماس با من</a>
    </br>
    <a href="/articles/" title="مقالات و اخبار">مقالات</a>

    {% for article in articles %}
    <h2><a href = "{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>    
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    {% endfor %}
</div>
{% endblock content %}
       

templates/home.html
{% extends "base.html" %}
{% block title %}
    خانه
{% endblock  %}

{% block content %}
<div class="container">
    <h1>صفحه نخست</h1>
    
    <a href="/" title="صفحه اصلی">صفحه آغازین</a>
    </br>
    <a href="/about/" title="درباره">دربارم میدونی؟</a>
    </br>
    <a href="/services/" title="خدمات">خدمات قابل ارائه</a>
    </br>
    <a href="/contact/" title="تماس بگیر باهام">تماس با من</a>
    </br>
    <a href="/articles/" title="مقالات و اخبار">مقالات</a>

    {% for article in articles %}
    <h2><a href = "{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>    
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    {% endfor %}
</div>
{% endblock content %}
       

templates/services.html
{% extends "base.html" %}
{% block title %}
    خدمات قابل ارائه
{% endblock  %}

{% block content %}
<div class="container">
    <h1>خدمات قابل ارائه ما</h1>
    
    <a href="/" title="صفحه اصلی">صفحه آغازین</a>
    </br>
    <a href="/about/" title="درباره">دربارم میدونی؟</a>
    </br>
    <a href="/services/" title="خدمات">خدمات قابل ارائه</a>
    </br>
    <a href="/contact/" title="تماس بگیر باهام">تماس با من</a>
    </br>
    <a href="/articles/" title="مقالات و اخبار">مقالات</a>

    {% for article in articles %}
    <h2><a href = "{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>    
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    {% endfor %}
</div>
{% endblock content %}
       